name: Publish

on:
  push:
    branches: [ master ]


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.301

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./ServerLibrary

      - name: Build package into a dll
        run: dotnet build -c Release
        working-directory: ./ServerLibrary

      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ./ServerLibrary/SimpleServerMin.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        working-directory: ./ServerLibrary

